export * from './member-base/member-base.component';
export * from './member-dashboard/member-dashboard.component';
export * from './member-detail/member-detail.component';
export * from './update-detail/update-detail.component';
export * from './update-email/update-email.component';
export * from './update-email-or-phone/update-email-or-phone.component';
export * from './update-password/update-password.component';
export * from './update-phone/update-phone.component';
export * from './update-photo/update-photo.component';
