export enum UserType {
  USER = 'USER',
  PROFESSIONAL = 'PROFESSIONAL',
  BUSINESS = 'BUSINESS'
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER'
}

export enum MemberStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DISABLED = 'DISABLED',
  BANNED = 'BANNED'
}


export enum ProfileVerificationStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  DISAPPROVED = 'DISAPPROVED',
  APPROVED = 'APPROVED'
}


export enum RoleType {
  SUPER_ADMINISTRATOR = 'SUPER_ADMINISTRATOR',
  ADMINISTRATOR = 'ADMINISTRATOR',
  REFRESH_TOKEN_USER = 'REFRESH_TOKEN_USER',
  PRE_VERIFIED_USER = 'PRE_VERIFIED_USER',
  PRE_AUTHENTICATED_USER = 'PRE_AUTHENTICATED_USER',
  USER = 'USER',
  CONTRIBUTOR = 'CONTRIBUTOR',
  RESET_PASSWORD_USER = 'RESET_PASSWORD_USER'
}

