name: Fleen Historia UI Workflow
run-name: UI Run
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build application
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install NPM and Build Angular Project
        run: |
          npm install
          npm run build
