name: Fleen Historia UI Workflow
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy application
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install NPM packages
        run: npm install

      - name: Build Project
        run: npm run build:prod

      - name: Run Tests
        run: npm run test:prod

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Print S3 Bucket Name
        run: |
          echo "S3 Bucket Name: ${{ secrets.S3_BUCKET_NAME }}"

      - name: Remove files from s3 buckets
        run: aws s3 rm --recursive s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.S3_STAGING_FOLDER }}

      - name: Copy to S3 Bucket
        run: aws s3 cp ./dist/fleen-historia-ui/ s3://${{ secrets.S3_BUCKET_NAME }} --recursive

      - name: clear cache
        run: aws cloudfront create-invalidation --distribution-id "${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION_ID }}" --paths "/*"
